# Generated by Django 3.2.25 on 2024-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('verification_image', models.ImageField(upload_to='verification_images/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
