# Generated by Django 3.2.25 on 2024-09-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milble_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
