# Generated by Django 3.2.25 on 2024-09-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milble_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='question3',
        ),
    ]
