# Generated by Django 3.2.25 on 2024-09-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milble_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='unit',
            field=models.CharField(default='default_unit_value', max_length=255),
            preserve_default=False,
        ),
    ]
