# Generated by Django 3.2.25 on 2024-09-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milble_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
