# Generated by Django 3.2.25 on 2024-09-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milble_app', '0002_auto_20240926_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
