# Generated by Django 3.2.25 on 2024-10-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milble_app', '0006_unit_subscriber_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='milble_app__post_id_180a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='milble_app__created_21cdcb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['unit'], name='milble_app__unit_id_5f43e2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='milble_app__categor_0d3639_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='milble_app__created_c48807_idx'),
        ),
    ]
